{% set version = "1.19.3" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-maldiquant
  version: {{ version|replace("-", "_") }}

source:
  fn: MALDIquant_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/MALDIquant_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/MALDIquant/MALDIquant_{{ version }}.tar.gz
  sha256: a730327c1f8d053d29e558636736b7b66d0671a009e0004720b869d2c76ff32c

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('MALDIquant')"  # [not win]
    - "\"%R%\" -e \"library('MALDIquant')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/MALDIquant/index.html
  license: GPL (>= 3)
  summary: A complete analysis pipeline for matrix-assisted laser desorption/ionization-time-of-flight
    (MALDI-TOF) and other two-dimensional mass spectrometry data. In addition to commonly
    used plotting and processing methods it includes distinctive features, namely baseline
    subtraction methods such as morphological filters (TopHat) or the statistics-sensitive
    non-linear iterative peak-clipping algorithm (SNIP), peak alignment using warping
    functions, handling of replicated measurements as well as allowing spectra with
    different resolutions.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
   recipe-maintainers:
    - dpryan79
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
