appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: Btqq7kVpPzpZba/LFp7lnal5eqyDddpl9X7z7IJIR/VKLhDw28wus6zFCdHuYOeVyQMh+5SqXdiCAffLkEZWbb4OwfZmYNc4rR+IsP0XysxynI4O7kC+30MxZFjaXWuVYYHwZFi1uWZTmloVLDv4zol2CNbrQHkEcZ+N0OjO+sEs5OCaEvyD3JNVZfSAtOrby+M5akPfMoYp/KwkE5exD32VNzP27KVm04HUWz04wozIqaHmr7f2Fik7hwFAaann68ql5SEWmsqFOsg5M7ZWnckU/4emLivIceR8rd1LfZDsL1k2KGumYOF1x9gMVeHEL3rMODXY9nDPeIC3iDb0yuLuUVDcMzyV+U1PsTcLMHtMFvQ+vey6Nr5Fke0N4F73ktKfCyoYw0bxpsVrzxt+lt7k5qJRJKQHVPFu9wkq8vj/3yxmZH/OaNCfn895fyJgqmu/Ky+MrkNwi3zIArMjZfCtan5tWjEeKA1RCs6iX3jVTguI73KKtBh0KRM529covDWsPBJc8xHipiJpnVip7T0Lx7UM9/958UPRQyKA28GNFLL+X0ZxjO+UD1MKnhnIq+PnQkg8QbG7zrKeVLszej68qUZe9+VCF3vUKjsUaSnPJHmBQOxNOd9hC1htSGVB52uyh67hAa33ntv1saL7s++ee5G2YW2jzRhyRjl1T4Q=}
